### ISSUE TITLE
Problem in Executing the Code!!

### ISSUE THREAD

**Issue by Sharma-Prachi** [mon95/Sign-Language-and-Static-gesture-recognition-using-sklearn#1]
Hello Sreehari!!
I have copy pasted your code in PyCharm with Python 3.6 installed with Numpy, Scipy, skimage, scikit, everything. But while running the code it always gives this error - ModuleNotFoundError: No Module named 'skimage'. I have followed many solutions on internet regarding this problem but nothing is working. Kindly help me out in solving this problem as I am new to Python. 
Thanks in advance

**Comment by mon95** [comment]
Hi! Just ensure you have skimage installed. (My guess is it's not installed correctly)

To check if skimage is installed, one way is to do the following:
Open your terminal. Type python to enter the python console. 
Now type "import skimage" and check if any error comes up. If it does, install skimage following instructions on the internet. 

A more general suggestion would be, just install anaconda and start working with jupyter notebooks. All the common ML stuff comes preinstalled and installing anything is a breeze. Try running the code (.ipynb file) after installing anaconda.

**Comment by Sharma-Prachi** [comment]
Thank you Sreehari! I have installed anaconda3 and now there is no problem reflecting in the code due to installation errors while running it. :)
